[theme]
base            = "dark"
primaryColor    = "#ff7e00"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1a2e"
textColor       = "#fafafa"
font            = "sans serif"

[server]
headless        = true
enableCORS      = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
